#!/bin/bash
usage="compile [spectral|bgrid|fv|shallow|barotropic]"
doc="Compiles an executable for running a model from the GFDL Flexible
Modelling System. Includes a spectral model, a B-grid model, a finite-volume
model, a shallow-water model, anad a barotropic model.

Usage

  $usage
"
# Compiler flags
cwd=$(readlink -f ${0})
cwd=${cwd%/*}
cd $cwd
source header.sh
root=$cwd/../
optimization='-O3'
ncflags='-lnetcdff -lnetcdf -lhdf5 -lhdf5_hl'
cppdefs='-Duse_libMPI -Duse_netCDF'
optimization='-O3' # O2 or O3? more optimization can actually be *slower*, but GFDL default was O3 so maybe not; https://stackoverflow.com/a/19985801/4970632
floatflags='-Ktrap=fp' # add =flag1,flag2,... for options; controls floating point exceptions; http://www.dartmouth.edu/~rc/HPC/man/pgf90.html
ncflags='-lnetcdff -lnetcdf -lhdf5 -lhdf5_hl' # include netcdf libs
mpflags='-Mmpi=mpich' # special 'pgflags', adds flags -L$MPILIB -lfmpich -lmpich; http://www.dartmouth.edu/~rc/HPC/man/pgf90.html
cppdefs='-Duse_libMPI -Duse_netCDF' # not sure what this does
# Host-specific settings
case ${HOSTNAME%%.*} in
  cheyenne*)
    # Basic libraries, with links to fortran compilers
    # Cheyenne uses a compiler wrapper mpif90 that handles all mpi flags,
    # so use mpif90/mpiifort (identical) instead of ifort
    # Also use Intel MPI or openmpi instead of default mpt
    # See: https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/running-jobs/intel-mpi-and-open-mpi
    module load intel &>/dev/null
    module load netcdf &>/dev/null
    module load impi &>/dev/null
    lib=$NETCDF/lib
    include=$NETCDF/include
    fortran=mpiifort
    cpp=mpiicc
    ldflags='-qopenmp' # see: https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/code-development-support/compiling-code
  ;; monde) # where code is compiled
    lib=/usr/lib64/mpich/lib
    include=/usr/include/mpich-x86_64
    fortran=pgf90
    cpp=pgcc
    fflags='-Ktrap=fp' # see: http://www.dartmouth.edu/~rc/HPC/man/pgf90.html
    ldflags='-Mmpi=mpich'
  ;; euclid) # everything is bunched together
    include=/usr/local/include
    lib=/usr/local/lib
    fortran=pgf90
    cpp=pgcc
    fflags='-Ktrap=fp'
    ldflags='-Mmpi=mpich'
  ;; *) raise "Unknown host, must configure library and binary locations before running." ;;
esac

# Parse input
while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help) echo "$doc" && exit 0 ;;
    -*) raise "Unknown argument \"$1\"." ;;
    *)
      [ -n "$model" ] && raise "Must specify just one model name."
      model=$1
      pathnames=$root/path_names_${model}
      [ -r $pathnames ] || raise "Invalid model \"${model}\" -- could not find file \"$pathnames\"."
      ;;
  esac
  shift
done
[ -z "$model" ] && raise "Must specify model name."
# Files
mkmf=$root/bin/mkmf                            # path to executable mkmf
mkmftemplate=$root/bin/mkmf.template           # template of most basic settings
mppnsource=$root/postprocessing/mppnccombine.c # source code
[ -d bin ] || mkdir bin
[ -r $mppnsource ]   || raise "Could not find mppnccombine source code."
[ -r $mkmftemplate ] || raise "Could not find Makefile template."
[ -r $mkmf ]         || raise "Could not find Makefile-generating utility $mkmf."

# Create mppnccombine
# NOTE: Don't compile with mpi support, just runs it a bunch of times
time=$(date +%s)
echo "Generating mppnccombine executable..."
$cpp -O -o bin/mppnccombine.x -L$lib -I$include $ncflags $mppnsource

# Build makefile template (assumes pgi bin is on $PATH)
cd bin # move to source directory
cat > mkmf.template << DELIM
CC = $cpp
FC = $fortran
LD = $fortran
CPPFLAGS =
FFLAGS = -r8 -pc 64 $fflags $optimization
LDFLAGS = -L$lib $ncflags $ldflags
LIST = -Mlist
DELIM
cat $mkmftemplate >> mkmf.template # appends provided template to custom defs

# Create makefile
echo "Generating Makefile..."
$mkmf -p ${model}.x -t mkmf.template -c "$cppdefs" -a $root $pathnames \
  $root/src/shared/mpp/include $root/src/shared/include ${include[@]} # the other include files
[ $? -ne 0 ] && raise "Mppnccombine compilation failed."

# Compile source
echo "Compiling source code..."
make -f Makefile
[ $? -ne 0 ] && raise "Model compilation failed."
cp *.x ../ 2>/dev/null
echo "This script took $(($(date +%s) - $time)) seconds."

